version: '3'
services: 
  db:
    image: mongo:latest
    ports:
      - 27800:27017
    volumes:
      - vmongo:/data/db
  backend:
    build: ./backend
    ports:
      - 5000:3000
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend


volumes:
  vmongo:


